server:
  port: 8082
  servlet:
    context-path: '/api-estetica/'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bdestetica
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob:
          non_contextual_creation: true
    properties:
      hibernate:
        show_sql: true
app:
  security:
    jwt:
      secret: "wPpL9oZ7uZc3s8vDnH1mTy2aXQ+YbS3GkLzjWnM0oEhqV8yC7T3p6BfT1rN5dJ2w"
      expiration-seconds: 3600
        