server:
  port: ${PORT}
  servlet:
    context-path: '/api-estetica/'

spring:
  datasource:
    ##jdbc:postgresql://localhost:5432/bdestetica
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob:
          non_contextual_creation: true
    properties:
      hibernate:
        show_sql: true
app:
  security:
    jwt:
      secret: ${JWT_SECRET:adYSgHkJQbZrSJRchQowNSj7KRjZENHvJMub2noeq7m0CYdH7d1cCjvavGdsoz6/}
      expiration-seconds: 3600
        