# Porta em que o backend vai rodar. 8080 é o padrão do Spring Boot.
server:
  port: 8082
  servlet:
    context-path: '/api-estetica'

spring:
  datasource:
    # URL de conexão para o seu banco de dados local
    url: jdbc:postgresql://localhost:5432/BancoEstetica
    # Seu usuário do Postgres
    username: postgres
    # Sua senha do Postgres
    password: 123
  jpa:
    hibernate:
      # 'update' tenta atualizar o banco com base nos seus models.
      # É bom para desenvolvimento.
      ddl-auto: update
    properties:
      hibernate:
        # Mostra os comandos SQL no console. Ótimo para debugar.
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  security:
    jwt:
      # Chave secreta para assinar os tokens.
      # Para desenvolvimento local, esta está ótima.
      secret: minhamarcadecafesecretaparaassinartokensjwt_123456
      # Tempo de validade do token (1 hora)
      expiration-seconds: 3600
        