# Configuração para ambiente de produção (Railway)
server:
  port: ${PORT:8080}
  servlet:
    context-path: '/api-estetica/'
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

spring:
  datasource:
    url: ${DATABASE_URL:${DB_URL}}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
  
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob:
          non_contextual_creation: true
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        jdbc:
          batch_size: 20
        cache:
          use_second_level_cache: false
    open-in-view: false
  
  # Configurações de segurança para produção
  security:
    require-ssl: false

# Configurações da aplicação
app:
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration-seconds: ${JWT_EXPIRATION:3600}

# Configurações de CORS para produção
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://*.railway.app,http://localhost:3000,http://localhost:5173}

# Configurações de logging
logging:
  level:
    com.esc2.api.estetica: INFO
    org.springframework.security: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Configurações do actuator para health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
